### ISSUE TITLE
Invalid JSON response: "Unexpected token U in JSON at position 0"

### ISSUE THREAD

**Issue by jbfriedrich** [ndaidong/oembed-parser#39]
From what I understand, [Ghost](https://github.com/TryGhost/Ghost) is using the oembed-parser to allow users to embed videos in their blog posts. I tried to embed a Youtube video in one of my blog posts today and encountered the issue described in Ghost [issue 10624](https://github.com/TryGhost/Ghost/issues/10624). 

Youtube seems to deliver a response the parser is not expecting. The whole error message I receive is:

```
{
  "err": {
    "code": null,
    "domain": "https://mydomain.tld",
    "id": "95093690-a7bc-11e9-8a98-bdc933ed02ad",
    "level": "critical",
    "message": "invalid json response body at https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dcc-elFcs96Y reason: Unexpected token U in JSON at position 0",
    "name": "InternalServerError",
    "stack": "InternalServerError: invalid json response body at https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dcc-elFcs96Y reason: Unexpected token U in JSON at position 0\n    at new InternalServerError (/var/www/ghost/versions/2.25.7/node_modules/ghost-ignition/lib/errors/index.js:77:23)\n    at extract.catch (/var/www/ghost/versions/2.25.7/core/server/api/v2/oembed.js:62:43)\n    at tryCatcher (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:517:31)\n    at Promise._settlePromise (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:574:18)\n    at Promise._settlePromise0 (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:619:10)\n    at Promise._settlePromises (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/promise.js:695:18)\n    at _drainQueueStep (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:138:12)\n    at _drainQueue (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:131:9)\n    at Async._drainQueues (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:147:5)\n    at Immediate.Async.drainQueues (/var/www/ghost/versions/2.25.7/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)",
    "statusCode": 500
  },
  "hostname": "<redacted>",
  "level": 50,
  "msg": "invalid json response body at https://www.youtube.com/oembed?format=json&url=http%3A%2F%2Fyoutube.com%2Fwatch%3Fv%3Dcc-elFcs96Y reason: Unexpected token U in JSON at position 0",
  "name": "Log",
  "pid": 23343,
  "req": {
    "headers": {
      "accept": "application/json, text/javascript, */*; q=0.01",
      "accept-encoding": "gzip, deflate, br",
      "accept-language": "en,en-US;q=0.9,de;q=0.8",
      "app-pragma": "no-cache",
      "connection": "close",
      "content-type": "application/json; charset=UTF-8",
      "cookie": "**REDACTED**",
      "dnt": "1",
      "host": "mydomain.tld",
      "referer": "https://mydomain.tld/ghost/",
      "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36",
      "x-forwarded-for": "1.2.3.4",
      "x-forwarded-proto": "https",
      "x-ghost-version": "2.25",
      "x-real-ip": "1.2.3.4",
      "x-requested-with": "XMLHttpRequest"
    },
    "meta": {
      "requestId": "894d5321-e801-4f2c-930f-d0f257460b77",
      "userId": "1"
    },
    "method": "GET",
    "originalUrl": "/ghost/api/v2/admin/oembed/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dcc-elFcs96Y",
    "params": {},
    "query": {
      "url": "https://www.youtube.com/watch?v=cc-elFcs96Y"
    },
    "url": "/oembed/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dcc-elFcs96Y"
  },
  "res": {
    "_headers": {
      "cache-control": "no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0",
      "content-length": "386",
      "content-type": "application/json; charset=utf-8",
      "etag": "W/\"182-+So45N9SFD0nfP2kp+OfniY4gac\"",
      "vary": "Accept-Encoding",
      "x-powered-by": "Express"
    },
    "responseTime": "182ms",
    "statusCode": 500
  },
  "time": "2019-07-16T11:26:40.769Z",
  "v": 0
}
```

As far as I could reproduce, the issue is not with all videos, quite the contrary. So far I encountered the issue just with [this one video](https://www.youtube.com/watch?v=cc-elFcs96Y). This [video](https://www.youtube.com/watch?v=9zinZmE3Ogk), for example, works fine.

**Comment by ndaidong** [comment]
@jbfriedrich thank you

**Comment by ndaidong** [comment]
@jbfriedrich hello, after several test I always get no problem with the video you provided (cc-elFcs96Y).

**Comment by jbfriedrich** [comment]
Yes, a day after I filed the report, Youtube did not show the behavior anymore. It seems that this happens to videos only sometimes, and after a while the issue is gone – on its own.

**Comment by ndaidong** [comment]
@jbfriedrich yes, it looks like something went wrong at your test, caused invalid JSON response. Let's me know if you get it again. Thanks.
